# SPDX-FileCopyrightText: 2025 László Vaskó <opensource@accounts.vlaci.email>
#
# SPDX-License-Identifier: EUPL-1.2

"""Contains a more performant and complete implementation of fnmatch."""


def fnmatch(pattern: str, value: str, *flags: Flag) -> bool: ...


class Flag:
    EMPTY: Flag = ...
    GLOB_STAR: Flag = ...
    BRACKET_EXPANSION: Flag = ...
    BRACE_EXPANSION: Flag = ...
    NEGATE: Flag = ...
    ESCAPE: Flag = ...
    NO_PATH: Flag = ...
